CREATE TABLE public.gender_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name character varying NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gender_master_pkey PRIMARY KEY (id)
);