CREATE TABLE public.kindness_givers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NULL DEFAULT auth.uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  giver_name character varying NOT NULL,
  relationship_id bigint NULL,
  gender_id bigint NULL,
  CONSTRAINT kindness_givers_pkey PRIMARY KEY (id),
  CONSTRAINT kindness_givers_gender_id_fkey FOREIGN KEY (gender_id) REFERENCES gender_master(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT kindness_givers_relationship_id_fkey FOREIGN KEY (relationship_id) REFERENCES relationship_master(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT kindness_givers_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL
);