CREATE TABLE public.kindness_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NULL DEFAULT gen_random_uuid(),
  giver_id bigint NULL,
  content text NULL,
  updated_at timestamp without time zone NULL,
  CONSTRAINT kindness_records_pkey PRIMARY KEY (id),
  CONSTRAINT kindness_records_giver_id_fkey FOREIGN KEY (giver_id) REFERENCES kindness_givers(id),
  CONSTRAINT kindness_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
)