CREATE TABLE public.kindness_reflections (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  reflection_type_id bigint NULL,
  reflection_title text NULL,
  reflection_start_date date NULL,
  reflection_end_date date NULL,
  user_id uuid NULL DEFAULT gen_random_uuid(),
  CONSTRAINT kindness_reflections_pkey PRIMARY KEY (id),
  CONSTRAINT kindness_reflections_reflection_type_id_fkey FOREIGN KEY (reflection_type_id) REFERENCES reflection_type_master(id),
  CONSTRAINT kindness_reflections_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
)