CREATE TABLE public.kindness_givers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NULL DEFAULT auth.uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  giver_name character varying NOT NULL,
  relationship_id bigint NULL,
  gender_id bigint NULL,
  CONSTRAINT kindness_givers_pkey PRIMARY KEY (id),
  CONSTRAINT kindness_givers_gender_id_fkey FOREIGN KEY (gender_id) REFERENCES gender_master(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT kindness_givers_relationship_id_fkey FOREIGN KEY (relationship_id) REFERENCES relationship_master(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT kindness_givers_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- RLSを有効化
alter table kindness_givers enable row level security;

-- ポリシーを作成
create policy "Users can create a kindness_giver."
on kindness_givers for insert
to authenticated
with check ( (select auth.uid()) = user_id );

create policy "Users can update their own kindness_giver."
on kindness_givers for update
to authenticated
using ( (select auth.uid()) = user_id )
with check ( (select auth.uid()) = user_id );

create policy "Users can delete a kindness_giver."
on kindness_givers for delete
to authenticated
using ( (select auth.uid()) = user_id );

create policy "Users can view their own kindness_giver."
on kindness_givers for select
to authenticated
using ( (select auth.uid()) = user_id );