CREATE TABLE public.reflection_type_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  reflection_type_name text NULL,
  reflection_period bigint NULL,
  CONSTRAINT reflection_type_master_pkey PRIMARY KEY (id)
)