CREATE TABLE public.relationship_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name character varying NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT relationship_master_pkey PRIMARY KEY (id)
);