CREATE TABLE public.balance_scores (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NULL DEFAULT gen_random_uuid(),
  week_start_date date NULL,
  week_end_date date NULL,
  sent_count bigint NULL,
  sent_uu bigint NULL,
  receive_count bigint NULL,
  reveice_uu bigint NULL,
  supporting_score bigint NULL,
  supported_score bigint NULL,
  supporting_score_norm double precision NULL,
  supported_score_norm double precision NULL,
  balance_score bigint NULL,
  CONSTRAINT balance_scores_pkey PRIMARY KEY (id),
  CONSTRAINT balance_scores_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);