CREATE TABLE public.gender_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name character varying NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gender_master_pkey PRIMARY KEY (id)
);

comment on table public.gender_master is '性別のマスタテーブル';

comment on column gender_master.id is '性別ID';
comment on column gender_master.name is '性別名';
comment on column gender_master.created_at is '作成日';

-- RLSを有効化
ALTER TABLE gender_master ENABLE ROW LEVEL SECURITY;

-- 認証済みユーザーは全ての性別データを読み取り可能
CREATE POLICY "Authenticated users can view all gender_master data."
ON gender_master FOR SELECT
TO authenticated
USING (true);