CREATE TABLE public.kindness_givers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NULL DEFAULT auth.uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  giver_name character varying NOT NULL,
  relationship_id bigint NULL,
  gender_id bigint NULL,
  CONSTRAINT kindness_givers_pkey PRIMARY KEY (id),
  CONSTRAINT kindness_givers_gender_id_fkey FOREIGN KEY (gender_id) REFERENCES gender_master(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT kindness_givers_relationship_id_fkey FOREIGN KEY (relationship_id) REFERENCES relationship_master(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT kindness_givers_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- RLSを有効化
alter table kindness_givers enable row level security;

-- ポリシーを作成
CREATE POLICY "Users can create a kindness_giver."
ON kindness_givers FOR INSERT
TO authenticated
WITH CHECK ( (SELECT auth.uid()) = user_id );

CREATE POLICY "Users can update their own kindness_giver."
ON kindness_givers FOR UPDATE
TO authenticated
USING ( (SELECT auth.uid()) = user_id )
WITH CHECK ( (SELECT auth.uid()) = user_id );

CREATE POLICY "Users can delete a kindness_giver."
ON kindness_givers FOR DELETE
TO authenticated
USING ( (SELECT auth.uid()) = user_id );

CREATE POLICY "Users can view their own kindness_giver."
ON kindness_givers FOR SELECT
USING ( (SELECT auth.uid()) = user_id );