CREATE TABLE public.reflection_type_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  reflection_type_name text NULL,
  reflection_period bigint NULL,
  CONSTRAINT reflection_type_master_pkey PRIMARY KEY (id)
);

comment on table public.reflection_type_master is 'リフレクション種別のマスタテーブル';

comment on column reflection_type_master.id is 'リフレクション種別ID';
comment on column reflection_type_master.created_at is '作成日';
comment on column reflection_type_master.reflection_type_name is 'リフレクション種別名';
comment on column reflection_type_master.reflection_period is 'リフレクション期間（日数）';

-- RLSを有効化
ALTER TABLE reflection_type_master ENABLE ROW LEVEL SECURITY;

-- 認証済みユーザーは全てのリフレクション種別データを読み取り可能
CREATE POLICY "Authenticated users can view all reflection_type_master data."
ON reflection_type_master FOR SELECT
TO authenticated
USING (true);