CREATE TABLE public.relationship_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name character varying NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT relationship_master_pkey PRIMARY KEY (id)
);

comment on table public.relationship_master is '関係性マスタ';

comment on column relationship_master.id is '関係性ID';
comment on column relationship_master.name is '関係性名';
comment on column relationship_master.created_at is '作成日';

-- RLSを有効化
ALTER TABLE relationship_master ENABLE ROW LEVEL SECURITY;

-- 認証済みユーザーは全ての関係性データを読み取り可能
CREATE POLICY "Authenticated users can view all relationship_master data."
ON relationship_master FOR SELECT
TO authenticated
USING (true);